// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifgpsdbltiggscpllvxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmZ3BzZGJsdGlnZ3NjcGxsdnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTYzMzQsImV4cCI6MjA2ODA5MjMzNH0.vgGsYqRfigFlJN2cgEGQa_dt5Ks4H0v0BoVXzc4QKlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});